from routes.health import health_router
from routes.statistics import statistics_router
from routes.creator import creator_router
from routes.account import account_router
from routes.post import post_router
from routes.collection import collection_router
from routes.file import file_router
from routes.queue import queue_router
from routes.init import init_router
from routes.system import system_router
