name: Release

on:
  push:
    tags-ignore:
      - "*-rc*"
      - "*-beta*"
      - "*-alpha*"
      - "*-dev*"
      - "*-pre*"
      - "*preRelease*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # -------------------------
      # 1. Build frontend
      # -------------------------
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # -------------------------
      # 2. Package files
      # -------------------------
      - name: Package release
        run: |
          mkdir release
          cp -r build/client release/dist
          cp -r api release/api
          cp requirements.txt release/api
          cp nginx_entrypoint.sh release/
          tar -czf release.tar.gz release

      # -------------------------
      # 3. Create GitHub Release
      # -------------------------
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          files: release.tar.gz
          generate_release_notes: true
          make_latest: ${{ !contains(github.ref_name, 'beta') && !contains(github.ref_name, 'rc') }}